---
# Enable container-based infrastructure
sudo: false

language: ruby

cache: bundler

services:
  - postgresql

rvm:
  - 2.3.0

bundler_args: --without darwin

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=travis

script:
  - bundle exec rubocop -Dc .rubocop.yml
  - RAILS_ENV=travis bundle exec rubocop

notifications:
  email: false