---
# Enable container-based infrastructure
sudo: false

language: ruby

cache: bundler

rvm:
  - 2.3.0

bundler_args: --without darwin

script:
  - bundle exec rake travis

notifications:
  email: false