---
# Enable container-based infrastructure
sudo: false

env:
  - TEST_DB_REST_API_SERVER_NAME=travis_ci_test
  - TEST_DB_REST_API_SERVER_USERNAME=postgres
  - TEST_DB_REST_API_SERVER_PASSWORD=''
  - TEST_DB_REST_API_SERVER_HOST=localhost

language: ruby

cache: bundler

services:
  - postgresql

rvm:
  - 2.3.0

bundler_args: --without darwin

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rake travis

notifications:
  email: false