---
# Enable container-based infrastructure
sudo: false

language: ruby

cache: bundler

services:
  - postgresql

rvm:
  - 2.3.0

bundler_args: --without darwin

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rake travis RAILS_ENV=travis

notifications:
  email: false