default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV["DB_REST_API_SERVER_NAME"] %>
  username: <%= ENV["DB_REST_API_SERVER_USERNAME"] %>
  password: <%= ENV["DB_REST_API_SERVER_PASSWORD"] %>
  host: <%= ENV["DB_REST_API_SERVER_HOST"] %>

test:
  <<: *default
  database: <%= ENV["DB_REST_API_SERVER_NAME"] %>
  username: <%= ENV["DB_REST_API_SERVER_USERNAME"] %>
  password: <%= ENV["DB_REST_API_SERVER_PASSWORD"] %>
  host: <%= ENV["DB_REST_API_SERVER_HOST"] %>

production:
  <<: *default
  database: <%= ENV["DB_REST_API_SERVER_NAME"] %>
  username: <%= ENV["DB_REST_API_SERVER_USERNAME"] %>
  password: <%= ENV["DB_REST_API_SERVER_PASSWORD"] %>
  host: <%= ENV["DB_REST_API_SERVER_HOST"] %>